backend:
  name: git-gateway
  repo: melvitax/liliflower.com 
  branch: master 

publish_mode: editorial_workflow
base_url: http://liliflower.com
media_folder: "images/uploads" 

collections:
  - name: "section" 
    label: "Section" 
    files: 
      - label: "Intro"
        name: "intro"
        file: "_data/intro.yml"
          - {label: Line 1, name: line1, widget: string}
          - {label: Line 2, name: line2, widget: string}
          - {label: Call To Action, name: calltoaction, widget: string}
      - label: "Welcome"
        name: "welcome"
        file: "_data/welcome.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Content, name: content, widget: markdown}
      - label: "Services"
        name: "services"
        file: "_data/services.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Call To Action, name: calltoaction, widget: string}
          - label: Packages
            name: packages
            widget: list
            create: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Descriptiom, name: description, widget: string}
      - label: "Resources"
        name: "resources"
        file: "_data/resources.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: URL, name: link, widget: string}
      - label: "Testimonials"
        name: "testimonials"
        file: "_data/testimonials.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label:Testimonials
            name: testimonials
            widget: list
            create: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Program, name: program, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Quote, name: quote, widget: string}
      - label: "Affiliations"
        name: "affiliations"
        file: "_data/affiliations.yml"
        widget: list
        create: true
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: URL, name: url, widget: string}